#------------------------------------------------------------------------------#
# @brief:       Dockerfile permit/deny-list for building the VPP testbench
#               project.
# @author:      Matthew Giassa <mgiassa@cisco.com>
# @copyright:   (C) Cisco 2021.
#------------------------------------------------------------------------------#
# Ignore everything by default. Permit-list only.
*

# Entrypoint scripts and other artifacts.
!client_ddos.sh
!server_ddos.sh
!server_http.sh
!server_sql_injection.sh
!vpp_testbench_helpers.sh
!rules
!ddos_rules.txt
