#------------------------------------------------------------------------------#
# @brief:       Dockerfile for building the VPP testbench project.
# @author:      Matthew Giassa <mgiassa@cisco.com>
# @copyright:   (C) Cisco 2021.
#------------------------------------------------------------------------------#
# Baseline image both client and server inherit from.
FROM ubuntu:focal as baseline

# System packages.
RUN apt update -y && \
    DEBIAN_FRONTEND="noninteractive" apt install -y tzdata termshark && \
    apt install -y \
        apt-transport-https \
        axel \
        bash \
        binutils \
        bridge-utils \
        ca-certificates \
        coreutils \
        curl \
        gnupg \
        htop \
        iftop \
        iproute2 \
        iptables \
        iputils-ping \
        netcat \
        net-tools \
        nload \
        nmap \
        procps \
        python3 \
        python3-dev \
        python3-pip \
        sudo \
        wget \
        tcpdump \
        vim \
        libsctp1 \
        gcc \
        libpcre3-dev \ 
        zlib1g-dev \ 
        libluajit-5.1-dev \
        libpcap-dev openssl \ 
        libssl-dev \ 
        libnghttp2-dev \ 
        libdumbnet-dev \ 
        bison \ 
        flex \ 
        libdnet \ 
        autoconf \ 
        libtool \
        && \
    apt clean -y && \
    apt-get install -y iperf
# Snort install
RUN mkdir ~/snort_src && cd ~/snort_src && \
    wget https://www.snort.org/downloads/snort/daq-2.0.7.tar.gz && \
    tar -xvzf daq-2.0.7.tar.gz && \
    cd daq-2.0.7 && \
    autoreconf -f -i && \
    ./configure && make && sudo make install && \
    cd ~/snort_src && \
    wget https://www.snort.org/downloads/snort/snort-2.9.20.tar.gz && \
    tar -xvzf snort-2.9.20.tar.gz && \
    cd snort-2.9.20 && \
    ./configure --enable-sourcefire && make && sudo make install && \
    sudo ldconfig && \
    sudo ln -s /usr/local/bin/snort /usr/sbin/snort
# Snort setup
RUN sudo groupadd snort && \
    sudo useradd snort -r -s /sbin/nologin -c SNORT_IDS -g snort && \
    sudo mkdir -p /etc/snort/rules && \
    sudo mkdir /var/log/snort && \
    sudo mkdir /usr/local/lib/snort_dynamicrules && \
    sudo chmod -R 5775 /etc/snort && \
    sudo chmod -R 5775 /var/log/snort && \
    sudo chmod -R 5775 /usr/local/lib/snort_dynamicrules && \
    sudo chown -R snort:snort /etc/snort && \
    sudo chown -R snort:snort /var/log/snort && \
    sudo chown -R snort:snort /usr/local/lib/snort_dynamicrules && \
    sudo touch /etc/snort/rules/white_list.rules && \
    sudo touch /etc/snort/rules/black_list.rules && \
    sudo touch /etc/snort/rules/local.rules && \
    sudo cp ~/snort_src/snort-2.9.20/etc/*.conf* /etc/snort && \
    sudo cp ~/snort_src/snort-2.9.20/etc/*.map /etc/snort
# Python packages.
RUN python3 -m pip install \
    scapy

# VPP.
RUN bash -c "curl -L https://packagecloud.io/fdio/master/gpgkey | apt-key add -" && \
    bash -c "echo \"deb [trusted=yes] https://packagecloud.io/fdio/release/ubuntu focal main\" >> /etc/apt/sources.list.d/99fd.io.list" && \
    apt update && \
    apt install -y \
        vpp \
        vpp-plugin-core \
        vpp-plugin-dpdk \
    && \
    apt clean -y

# Used by client/server entrypoint scripts.
ADD vpp_testbench_helpers.sh /


#------------------------------------------------------------------------------#
# Client image.
FROM baseline as client_img
# Enable a health probe.
ARG HEALTHCHECK_PORT=8080
ENV HEALTHCHECK_PORT_RUNTIME="${HEALTHCHECK_PORT}"
HEALTHCHECK CMD curl --fail "http://localhost:$HEALTHCHECK_PORT_RUNTIME" || exit 1
# Image-specific overrides.
ADD ./client_ddos.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
 

#------------------------------------------------------------------------------#
# Server image.
FROM baseline as server_img
# Enable a health probe.
ARG HEALTHCHECK_PORT=8080
ENV HEALTHCHECK_PORT_RUNTIME="${HEALTHCHECK_PORT}"
HEALTHCHECK CMD curl --fail "http://localhost:$HEALTHCHECK_PORT_RUNTIME" || exit 1
# Image-specific overrides.
ADD ./server_ddos.sh /entrypoint.sh
ADD rules /etc/snort/rules
ADD ./ddos_rules.txt /etc/snort/rules/ddos_rules.txt
ENTRYPOINT ["/entrypoint.sh"]

